#!/bin/sh

# Create a output directory to store the files created by Spin
mkdir -p output && rm -rf output/* && cd output

# Run spin on the model file
spin -a ../src/promela/model.pml

# Build the analyzer using gcc
gcc -Wno-format-overflow -o analyzer pan.c

# Run the analyzer with the -a flag to check for assertion violations
# -a = check for assertion violations
# -f = check for LTL properties
./analyzer -a -f -N ../src/promela/model.pml

# If there is a violation, a trace will be generated in the output directory
# So, if the file exists, run spin again to get the counterexample
if [ -f ./model.pml.trail ]; then
	echo "Counterexample found. Running Spin to generate the trail file..."
	spin -k ./model.pml.trail ../src/promela/model.pml
fi

